[package]
name = "calc_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
calc_units = { version = "0.1.0", path = "../calc_units" }
proc-macro2 = "1.0.92"
quote = "1.0.37"
syn = "2.0.90"

[lib]
proc-macro = true
